
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/component/NavBar";
import { Roboto } from 'next/font/google';
import Footer from "@/component/Footer";
import FooterSection from "@/component/Footer";
import ScrollBasedVelocityReviewDemo from "@/component/scrollReview";
import { ToastContainer } from "react-toastify";
import Modal from "@/component/Modal";


const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700'], // choose what you need
  display: 'swap',
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const Avatar = async () => {
    console.log('d')
  }
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className={`min-h-full flex flex-col ${roboto.className}`}>
        <NavBar />
        <main>
          {children}
          
        </main>

        <ScrollBasedVelocityReviewDemo />

        <FooterSection />
        <ToastContainer 
          position="top-right"
          autoClose={3000}
        />
        <Modal />

      </body>
    </html>
  );
}
